# Generated by Django 4.2.7 on 2023-12-04 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_order_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='price',
        ),
    ]
