# Generated by Django 4.2.7 on 2023-12-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_order_products_id_remove_order_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.TextField(null=True),
        ),
    ]
